version: "3"

services:
  docker-database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: linux-dio
      MYSQL_DATABASE: dio-bootcamp
    ports:
      - 3306:3306
  app:
    image: docker-ts
    build: .
    ports:
      - 3000:3000
    depends_on:
      - docker-database
